let words = [            
    Card(word: "Labor, Stage 1", 
         taboo: ["cervix", "dilation", "contraction"]),
    Card(word: "Uterus",
         taboo: ["womb", "cervix", "baby"]),
    Card(word: "Oxytocin",
         taboo: ["uterotonic", "hormone", "estrogen"]),
    Card(word: "Betamethasone", 
         taboo: ["baby", "premature", "steroid"]),
    Card(word: "Chloroprocaine", 
         taboo: ["local anesthetic", "epidural", "c-section"]),
    Card(word: "Placenta Accreta", 
         taboo: ["uterus", "spiral arteries", "vasoconstriction"]),
    Card(word: "Methergine", 
         taboo: ["uterotonic", "hypertension", "methylergonovine"]),
    Card(word: "Lidocaine", 
         taboo: ["local anesthetic", "epidural", "c-section"]),
    Card(word: "TXA", 
         taboo: ["antifibrinolytic", "clot", "hemorrhage"]),
    Card(word: "Labor, Stage 2", 
         taboo: ["cervix", "dilation", "contraction"]),
    Card(word: "Placenta Accreta", 
         taboo: ["uterus", "spiral arteries", "vasoconstriction"]),
    Card(word: "DPE", 
         taboo: ["spinal needle", "CSE", "obesity"]),
    Card(word: "70K", 
         taboo: ["platelet count", "epidural hematoma", "safe"]),
    Card(word: "Cervical Cerclage", 
         taboo: ["cervix", "insufficiency", "spinal"]),
    Card(word: "Pre-eclampsia", 
         taboo: ["hypertension", "proteinuria", "end-organ dysfunction"]),
    Card(word: "Fibrinogen", 
         taboo: ["fibrin", "PPH", "clot"]),
    Card(word: "Left Uterine Displacement", 
         taboo: ["aortocaval", "compression", "hypotension"]),
    Card(word: "APGAR", 
         taboo: ["score", "baby", "number"]),
    Card(word: "Early Deceleration", 
         taboo: ["fetal heart tracing", "strip", "baby"]),
    Card(word: "Atony", 
         taboo: ["uterotonic", "hemabate", "methergine"]),
    Card(word: "AFE", 
         taboo: ["amniotic", "fluid", "baby"]),
    Card(word: "Respiratory Alkalosis", 
         taboo: ["metabolic disorder", "minute ventilation", "pH"]),
    Card(word: "Magnesium", 
         taboo: ["seizure", "eclampsia", "prevent"]),
    Card(word: "Nifedipine", 
         taboo: ["tocolytic", "hypertension", "calcium"]),
    Card(word: "FRC", 
         taboo: ["ERV", "RV", "desaturate"]),
    Card(word: "Heparin", 
         taboo: ["lovenox", "DVT", "medication"]),
    Card(word: "Aspirin", 
         taboo: ["medication", "PEC", "prevent"]),
    Card(word: "ECV", 
         taboo: ["baby", "breech", "turn"]),
    Card(word: "Heparin", 
         taboo: ["Lovenox", "DVT", "medication"]),
    Card(word: "Hemabate", 
         taboo: ["uterotonic", "asthma", "carboprost"]),
    Card(word: "ERAC", 
         taboo: ["multi-modal", "protocol", "TAP block"]),
    Card(word: "High Spinal", 
         taboo: ["unconscious", "seizure", "intrathecal"]),
    Card(word: "PDPH", 
         taboo: ["EBP", "epidural", "needle"]),
    Card(word: "EBP", 
         taboo: ["PDPH", "gold standard", "treatment"]),
    Card(word: "Bakri Balloon", 
         taboo: ["atony", "hemorrhage", "uterus"]),
    Card(word: "Placental Abruption", 
         taboo: ["complication", "emergent CD", "TOLAC"]),    
    Card(word: "Ligamentum Flavum", 
         taboo: ["epidural", "space", "dura"]),
    Card(word: "Morphine", 
         taboo: ["long acting", "analgesic", "pain"]),
    Card(word: "Test Dose", 
         taboo: ["intrathecal", "intravascular", "wrong"]),
]

